# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)
################################################################################################################################################
Competency.create([
								{:name => 'Camera', 	:priority => 2}, 
								{:name => 'Audio', 		:priority => 2}, 
								{:name => 'Television',:priority => 2}, 
								{:name => 'Computer',	:priority => 2}, 
								{:name => 'Telephone',:priority => 2}, 
								{:name => 'Task Team',:priority => 1}, 
								{:name => 'Sasu',			:priority => 1}
								])
################################################################################################################################################
#partner = Partner.create ({
#					:first_name => 'Jason',	
#					:last_name => 'Lizarraga',	
#					:employee_no => '789654321', 
#					:is_manager => true,
#					:is_temp => false})
#Contact.create({ 	:partner_id => partner.id, 
#									:telephone_no  => '07944055452', 
#									:address_line1 => '1542 New Avenue', 
#									:address_line2 => '',	
#									:city => 'Dagenham', 
#									:county => 'Essex', 
#									:post_code => 'RM12 3FR' })
#work_plan = WorkPlan.where(:partner_id => partner.id)[0]
#work_plan.update_attributes({
#					:partner_id => partner.id, 
#					:starting_week_no => '1', 
#					:holiday_entitle => '25', 
#					:holiday_taken => '5'})
#weekly_rota = WeeklyRota.create({:work_plan_id => work_plan.id})						

#ShiftTemplate.create([	
#						{:weekly_rota_id => weekly_rota.id, :name => partner.first_name + partner.last_name, :start_at => DateTime.parse("Sun, 1 Jan 2006 10:00:00 +0000"), :end_at => DateTime.parse("Sun, 1 Jan 2006 18:00:00 +0000"), :is_active => true},
#						{:weekly_rota_id => weekly_rota.id, :name => partner.first_name + partner.last_name, :start_at => DateTime.parse("Mon, 2 Jan 2006 9:00:00 +0000"), :end_at => DateTime.parse("Mon, 2 Jan 2006 17:00:00 +0000"), :is_active => true},
#						{:weekly_rota_id => weekly_rota.id, :name => partner.first_name + partner.last_name, :start_at => DateTime.parse("Tue, 3 Jan 2006 10:00:00 +0000"), :end_at => DateTime.parse("Tue, 3 Jan 2006 18:00:00 +0000"), :is_active => true},
#						{:weekly_rota_id => weekly_rota.id, :name => partner.first_name + partner.last_name, :start_at => DateTime.parse("Wed, 4 Jan 2006 9:00:00 +0000"), :end_at => DateTime.parse("Wed, 4 Jan 2006 17:00:00 +0000"), :is_active => true},
#						{:weekly_rota_id => weekly_rota.id, :name => partner.first_name + partner.last_name, :start_at => DateTime.parse("Thu, 5 Jan 2006 10:00:00 +0000"), :end_at => DateTime.parse("Thu, 5 Jan 2006 18:00:00 +0000"), :is_active => true},
#						{:weekly_rota_id => weekly_rota.id, :name => partner.first_name + partner.last_name, :start_at => DateTime.parse("Fri, 6 Jan 2006 10:00:00 +0000"), :end_at => DateTime.parse("Fri, 6 Jan 2006 18:00:00 +0000"), :is_active => false},
#						{:weekly_rota_id => weekly_rota.id, :name => partner.first_name + partner.last_name, :start_at => DateTime.parse("Sat, 7 Jan 2006 10:00:00 +0000"), :end_at => DateTime.parse("Sat, 7 Jan 2006 18:00:00 +0000"), :is_active => false}
#						])

#Holiday.create([	
#					{:work_plan_id => work_plan.id, :name =>partner.first_name + partner.last_name, :start_at => DateTime.parse("23 Jan 2011 10:00:00 +0000"), :end_at => DateTime.parse("23 Jan 2011 18:00:00 +0000")},
#					{:work_plan_id => work_plan.id, :name =>partner.first_name + partner.last_name, :start_at => DateTime.parse("24 Jan 2011 9:00:00 +0000"), :end_at => DateTime.parse("24 Jan 2011 17:00:00 +0000")},
#					{:work_plan_id => work_plan.id, :name =>partner.first_name + partner.last_name, :start_at => DateTime.parse("25 Jan 2011 10:00:00 +0000"), :end_at => DateTime.parse("25 Jan 2011 18:00:00 +0000")},
#					{:work_plan_id => work_plan.id, :name =>partner.first_name + partner.last_name, :start_at => DateTime.parse("26 Jan 2011 9:00:00 +0000"), :end_at => DateTime.parse("26 Jan 2011 17:00:00 +0000")},
#					{:work_plan_id => work_plan.id, :name =>partner.first_name + partner.last_name, :start_at => DateTime.parse("27 Jan 2011 10:00:00 +0000"), :end_at => DateTime.parse("27 Jan 2011 18:00:00 +0000")},
#					])
################################################################################################################################################
partner = Partner.create({	
						:first_name => 'Chris',	
						:last_name => 'Gungaloo', 
						:employee_no => '123456789', 
						:is_manager => true, 
						:is_temp => false}
						)
Contact.create({ 	:partner_id => partner.id,	
									:telephone_no  => '07960577214',	
									:address_line1 => '255 Morland Street', 
									:address_line2 => 'Croydon',	
									:city => 'London', 
									:county => '', 
									:post_code => 'CR0 3DE'})
################################################################################################################################################
partner = Partner.create({	
						:first_name => 'Nicola', 
						:last_name => 'Santen', 
						:employee_no => '741852963', 
						:is_manager => false,
						:is_temp => false })
Contact.create({ 	:partner_id => partner.id,	
									:telephone_no  => '02085412244',	
									:address_line1 => '1 Brocket Avenue', 
									:address_line2 => '', 
									:city => 'Chigwell',
									:county => 'Essex', 
									:post_code => 'IG4 5JE' })
################################################################################################################################################
partner = Partner.create({ 
							:first_name => 'John', 
							:last_name => 'Lewis', 
							:employee_no => '369258147',	
							:is_manager => false,
							:is_temp => true})
Contact.create({	:partner_id => partner.id, 
									:telephone_no  => '02074125465', 
									:address_line1 => 'Flat C', 
									:address_line2 => '245 Commercial Road', 
									:city => 'London',
									:county  => '', 
									:post_code => 'E3 5GH' })
################################################################################################################################################
Country.create([
		{:name => 'Afghanistan'},
		{:name => 'Albania'},
		{:name => 'Algeria'},
		{:name => 'Andorra'},
		{:name => 'Angola'},
		{:name => 'Antigua and Barbuda'},
		{:name => 'Argentina'},
		{:name => 'Armenia'},
		{:name => 'Australia'},
		{:name => 'Austria'},
		{:name => 'Azerbaijan'},
		{:name => 'Bahamas'},
		{:name => 'Bahrain'},
		{:name => 'Bangladesh'},
		{:name => 'Barbados'},
		{:name => 'Belarus'},
		{:name => 'Belgium'},
		{:name => 'Belize'},
		{:name => 'Benin'},
		{:name => 'Bhutan'},
		{:name => 'Bolivia'},
		{:name => 'Bosnia and Herzegovina'},
		{:name => 'Botswana'},
		{:name => 'Brazil'},
		{:name => 'Brunei'},
		{:name => 'Bulgaria'},
		{:name => 'Burkina Faso'},
		{:name => 'Burundi'},
		{:name => 'Cambodia'},
		{:name => 'Cameroon'},
		{:name => 'Canada'},
		{:name => 'Cape Verde'},
		{:name => 'Central African Republic'},
		{:name => 'Chad'},
		{:name => 'Chile'},
		{:name => 'China'},
		{:name => 'Colombia'},
		{:name => 'Comoros'},
		{:name => 'Congo'},
		{:name => 'Costa Rica'},
		{:name => 'Ivory Coast'},
		{:name => 'Croatia'},
		{:name => 'Cuba'},
		{:name => 'Cyprus'},
		{:name => 'Czech Republic'},
		{:name => 'Denmark'},
		{:name => 'Djibouti'},
		{:name => 'Dominica'},
		{:name => 'Dominican Republic'},
		{:name => 'Ecuador'},
		{:name => 'Egypt'},
		{:name => 'El Salvador'},
		{:name => 'Equatorial Guinea'},
		{:name => 'Eritrea'},
		{:name => 'Estonia'},
		{:name => 'Ethiopia'},
		{:name => 'Fiji'},
		{:name => 'Finland'},
		{:name => 'France'},
		{:name => 'Gabon'},
		{:name => 'Gambia'},
		{:name => 'Georgia'},
		{:name => 'Germany'},
		{:name => 'Ghana'},
		{:name => 'Greece'},
		{:name => 'Grenada'},
		{:name => 'Guatemala'},
		{:name => 'Guinea'},
		{:name => 'Guinea-Bissau'},
		{:name => 'Guyana'},
		{:name => 'Haiti'},
		{:name => 'Honduras'},
		{:name => 'Hungary'},
		{:name => 'Iceland'},
		{:name => 'India'},
		{:name => 'Indonesia'},
		{:name => 'Iran'},
		{:name => 'Iraq'},
		{:name => 'Ireland'},
		{:name => 'Israel'},
		{:name => 'Italy'},
		{:name => 'Jamaica'},
		{:name => 'Japan'},
		{:name => 'Jordan'},
		{:name => 'Kazakhstan'},
		{:name => 'Kenya'},
		{:name => 'Kiribati'},
		{:name => 'Korea (North)'},
		{:name => 'Korea (South)'},
		{:name => 'Kuwait'},
		{:name => 'Kyrgyzstan'},
		{:name => 'Laos'},
		{:name => 'Latvia'},
		{:name => 'Lebanon'},
		{:name => 'Lesotho'},
		{:name => 'Liberia'},
		{:name => 'Libya'},
		{:name => 'Liechtenstein'},
		{:name => 'Lithuania'},
		{:name => 'Luxembourg'},
		{:name => 'Macedonia'},
		{:name => 'Madagascar'},
		{:name => 'Malawi'},
		{:name => 'Malaysia'},
		{:name => 'Maldives'},
		{:name => 'Mali'},
		{:name => 'Malta'},
		{:name => 'Marshall Islands'},
		{:name => 'Mauritania'},
		{:name => 'Mauritius'},
		{:name => 'Mexico'},
		{:name => 'Micronesia'},
		{:name => 'Moldova'},
		{:name => 'Monaco'},
		{:name => 'Mongolia'},
		{:name => 'Montenegro'},
		{:name => 'Morocco'},
		{:name => 'Mozambique'},
		{:name => 'Myanmar (Burma)'},
		{:name => 'Namibia'},
		{:name => 'Nauru'},
		{:name => 'Nepal'},
		{:name => 'Netherlands'},
		{:name => 'New Zealand'},
		{:name => 'Nicaragua'},
		{:name => 'Niger'},
		{:name => 'Nigeria'},
		{:name => 'Norway'},
		{:name => 'Oman'},
		{:name => 'Pakistan'},
		{:name => 'Palau'},
		{:name => 'Panama'},
		{:name => 'Papua New Guinea'},
		{:name => 'Paraguay'},
		{:name => 'Peru'},
		{:name => 'Philippines'},
		{:name => 'Poland'},
		{:name => 'Portugal'},
		{:name => 'Qatar'},
		{:name => 'Romania'},
		{:name => 'Russia'},
		{:name => 'Rwanda'},
		{:name => 'Saint Kitts and Nevis'},
		{:name => 'Saint Lucia'},
		{:name => 'Saint Vincent and the Grenadines'},
		{:name => 'Samoa'},
		{:name => 'San Marino'},
		{:name => 'Sao Tome and Principe'},
		{:name => 'Saudi Arabia'},
		{:name => 'Senegal'},
		{:name => 'Serbia'},
		{:name => 'Seychelles'},
		{:name => 'Sierra Leone'},
		{:name => 'Singapore'},
		{:name => 'Slovakia'},
		{:name => 'Slovenia'},
		{:name => 'Solomon Islands'},
		{:name => 'Somalia'},
		{:name => 'South Africa'},
		{:name => 'Spain'},
		{:name => 'Sri Lanka'},
		{:name => 'Sudan'},
		{:name => 'Suriname'},
		{:name => 'Swaziland'},
		{:name => 'Sweden'},
		{:name => 'Switzerland'},
		{:name => 'Syria'},
		{:name => 'Tajikistan'},
		{:name => 'Tanzania'},
		{:name => 'Thailand'},
		{:name => 'Timor-Leste (East Timor)'},
		{:name => 'Togo'},
		{:name => 'Tonga'},
		{:name => 'Trinidad and Tobago'},
		{:name => 'Tunisia'},
		{:name => 'Turkey'},
		{:name => 'Turkmenistan'},
		{:name => 'Tuvalu'},
		{:name => 'Uganda'},
		{:name => 'Ukraine'},
		{:name => 'United Arab Emirates'},
		{:name => 'United Kingdom'},
		{:name => 'United States'},
		{:name => 'Uruguay'},
		{:name => 'Uzbekistan'},
		{:name => 'Vanuatu'},
		{:name => 'Vatican City'},
		{:name => 'Venezuela'},
		{:name => 'Vietnam'},
		{:name => 'Yemen'},
		{:name => 'Zambia'},
		{:name => 'Zimbabwe'}])
